site_name: ChômageLand
site_url: https://chomageland.fr

repo_url: https://github.com/BanaaNuts/ChomageLand-Web
repo_name: BanaaNuts/ChomageLand-Web
edit_uri: edit/main/docs/


nav:
    - 'Accueil': 'index.md'
    - 'Coordonnées':
        - 'Monde normal': 'coordonnees/coordonnees_normal.md'
        - 'Nether': 'coordonnees/coordonnees_nether.md'
        - 'End': 'coordonnees/coordonnees_end.md'
    - 'Commandes': 'commandes.md'
    - 'Multiverse': 'multiverse.md'
    - 'Guides':
        - 'Optimisation': 'guides/optimisation.md'
        - 'MultiMC': 'guides/multimc.md'
    - 'Plugins & autres': 'plugins.md'
    - 'Ressources': 'ressources.md'

theme:
    name: material
    features:
        - navigation.top
    icon:
        repo: fontawesome/brands/github
    logo: img/pole_emploi.png
    favicon: img/pole_emploi.png
    palette: 
        # Palette toggle for dark mode
        scheme: slate

plugins:
    - search
    - git-revision-date-localized:
        enable_creation_date: true
        type: iso_datetime
        fallback_to_build_date: true

markdown_extensions:
    - tables
    - admonition
    - attr_list
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.snippets:
        check_paths: true
        base_path:
        - docs/_snippets
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: true